Change arguments in the big fix
flaresimulations/synthesizer-grids pull request #49
Opened 2024-02-06 15:12 UTC by stephenmwilkins

Replaced `synthesizer_data_dir` argument with `grid_dir` and `input_dir` to avoid use of implicit subdirectories.

## Issue Type

- Bug
- Document
- Enhancement

## Checklist
- [ ] I have read the [CONTRIBUTING.md]()
- [ ] I have added docstrings to all methods
- [ ] I have added sufficient comments to all lines
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no pep8 errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-02-06 15:16 UTC, WillJRoper commented
Of course for now the BPASS scripts won't run regardless.

2024-02-07 16:24 UTC, christopherlovell commented
Could you double check that these files have been run through black? I can see a couple instances where there are non compliant formatting issues. We will be moving to this soon so best to do now

2024-02-07 16:25 UTC, christopherlovell requested changes
Could you double check that these files have been run through black? I can see a couple instances where there are non compliant formatting issues. We will be moving to this soon so best to do now

2024-02-15 09:46 UTC, stephenmwilkins commented
> Could you double check that these files have been run through black? I can see a couple instances where there are non compliant formatting issues. We will be moving to this soon so best to do now

I believe this is now fixed (swapped to using black instead of autopep8 in VSCode). I have not completely fixed the install_bpass<version> since they still don't work.

2024-02-15 09:58 UTC, christopherlovell commented
> > Could you double check that these files have been run through black? I can see a couple instances where there are non compliant formatting issues. We will be moving to this soon so best to do now
> 
> I believe this is now fixed (swapped to using black instead of autopep8 in VSCode). I have not completely fixed the install_bpass since they still don't work.

Is this still a Hoki issue? I believe @WillJRoper fixed this, unless it hasn't been merged yet

2024-02-15 10:33 UTC, stephenmwilkins commented
@christopherlovell @WillJRoper has a PR that hasn't been accepted yet with no response from the authors. We might have to re-write our own parser.

2024-02-15 10:50 UTC, stephenmwilkins commented
@WillJRoper noted that we could force the version of astropy while hoping Hoki update.

2024-02-22 14:10 UTC, merged

2024-02-22 14:12 UTC, christopherlovell commented on src/synthesizer_grids/cloudy/create_single_cloudy_input.py
I quite like this. Good for testing as you say